Objectives:
  - "Allow for rapid creation of Node.js Modules."

Features:
  - "Adds as a devDependency to modules it spawns."
  - "Extendable by other scaffold modules."
  - "Handles project.yml parsing."
  - "Exposes several automated Mocha tests to children."

Methods:
  - "getProject"  
  - "testMethods"
  - "testClasses"
  - "testStructure"
  - "debug"

CLI:
  - "scaffold-module"
  - "scaffold-module create"
  - "scaffold-module update"
  - "scaffold-module validate"
