objectives:
  - "Allow for rapid creation of Node.js Modules."

features:
  - "Adds as a devDependency to modules it spawns."
  - "Extendable by other scaffold modules."
  - "Handles project.yml parsing."
  - "Exposes several automated Mocha tests to children."

methods:

tasks:
  - "scaffold-module"
  - "scaffold-module update"
  - "scaffold-module validate"
